### Feature Selection Advanced House Price Prediction
The main aim of this project is to predict the house price based on various features which we will discuss as we go ahead

Dataset to downloaded from the below link
https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

In [46]:
import pandas as pd
import numpy as np

In [47]:
dataset=pd.read_csv("X_train.csv")

In [48]:
dataset.head()

,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MoSold,YrSold,SaleType,SaleCondition,LotFrontage nan,MasVnrArea nan,GarageYrBlt nan,age_of_house,years_to_remod,years_to_garagebuilt
0,12.247694,0.235294,0.75,0.418208,0.366344,1.0,1.0,0.000000,0.333333,1.0,...,0.090909,0.50,0.666667,0.75,0.0,0.0,0.0,0.036765,0.098361,0.046729
1,12.109011,0.000000,0.75,0.495064,0.391317,1.0,1.0,0.000000,0.333333,1.0,...,0.363636,0.25,0.666667,0.75,0.0,0.0,0.0,0.227941,0.524590,0.289720
2,12.317167,0.235294,0.75,0.434909,0.422359,1.0,1.0,0.333333,0.333333,1.0,...,0.727273,0.50,0.666667,0.75,0.0,0.0,0.0,0.051471,0.114754,0.065421
3,11.849398,0.294118,0.75,0.388581,0.390295,1.0,1.0,0.333333,0.333333,1.0,...,0.090909,0.00,0.666667,0.00,0.0,0.0,0.0,0.669118,0.606557,0.074766
4,12.429216,0.235294,0.75,0.513123,0.468761,1.0,1.0,0.333333,0.333333,1.0,...,1.000000,0.50,0.666667,0.75,0.0,0.0,0.0,0.058824,0.147541,0.074766

In [49]:
y_train=dataset[['SalePrice']]
X_train=dataset.drop(columns=["SalePrice"],axis=1)

In [50]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel
feature_selection=SelectFromModel(Lasso(alpha=0.005,random_state=0))
feature_selection.fit(X_train,y_train)

SelectFromModel(estimator=Lasso(alpha=0.005, random_state=0))

In [51]:
selected_feature=X_train.columns[(feature_selection.get_support())]
print("total features : {}".format(X_train.shape[1]))
print("selected feature: {}".format(len(selected_feature)))

total features : 85
selected feature: 22

In [52]:
selected_feature

Index(['MSSubClass', 'MSZoning', 'Neighborhood', 'OverallQual', 'YearRemodAdd',
       'RoofStyle', 'BsmtQual', 'BsmtExposure', 'HeatingQC', 'CentralAir',
       '1stFlrSF', 'GrLivArea', 'BsmtFullBath', 'KitchenQual', 'Fireplaces',
       'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageCars', 'PavedDrive',
       'SaleCondition', 'years_to_remod'],
      dtype='object')

In [53]:
X_train=X_train[selected_feature]

In [54]:
X_train

,MSSubClass,MSZoning,Neighborhood,OverallQual,YearRemodAdd,RoofStyle,BsmtQual,BsmtExposure,HeatingQC,CentralAir,...,BsmtFullBath,KitchenQual,Fireplaces,FireplaceQu,GarageType,GarageFinish,GarageCars,PavedDrive,SaleCondition,years_to_remod
0,0.235294,0.75,0.636364,0.666667,0.883333,0.0,0.75,0.25,1.00,1.0,...,0.333333,0.666667,0.000000,0.2,0.8,0.666667,0.50,1.0,0.75,0.098361
1,0.000000,0.75,0.500000,0.555556,0.433333,0.0,0.75,1.00,1.00,1.0,...,0.000000,0.333333,0.333333,0.6,0.8,0.666667,0.50,1.0,0.75,0.524590
2,0.235294,0.75,0.636364,0.666667,0.866667,0.0,0.75,0.50,1.00,1.0,...,0.333333,0.666667,0.333333,0.6,0.8,0.666667,0.50,1.0,0.75,0.114754
3,0.294118,0.75,0.727273,0.666667,0.333333,0.0,0.50,0.25,0.75,1.0,...,0.333333,0.666667,0.333333,0.8,0.4,0.333333,0.75,1.0,0.00,0.606557
4,0.235294,0.75,1.000000,0.777778,0.833333,0.0,0.75,0.75,1.00,1.0,...,0.333333,0.666667,0.333333,0.6,0.8,0.666667,0.75,1.0,0.75,0.147541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.235294,0.75,0.590909,0.555556,0.833333,0.0,0.75,0.25,1.00,1.0,...,0.000000,0.333333,0.333333,0.6,0.8,0.666667,0.50,1.0,0.75,0.131148
1456,0.000000,0.75,0.545455,0.555556,0.633333,0.0,0.75,0.25,0.50,1.0,...,0.333333,0.333333,0.666667,0.6,0.8,0.333333,0.50,1.0,0.75,0.377049
1457,0.294118,0.75,0.727273,0.666667,0.933333,0.0,0.50,0.25,1.00,1.0,...,0.000000,0.666667,0.666667,0.8,0.8,0.666667,0.25,1.0,0.75,0.081967
1458,0.000000,0.75,0.363636,0.444444,0.766667,1.0,0.50,0.50,0.75,1.0,...,0.333333,0.666667,0.000000,0.2,0.8,0.333333,0.25,1.0,0.75,0.245902
1459,0.000000,0.75,0.227273,0.444444,0.250000,0.0,0.50,0.25,0.75,1.0,...,0.333333,0.333333,0.000000,0.2,0.8,1.000000,0.25,1.0,0.75,0.721311

In [55]:
X_train.to_csv("X_training.csv",index=False)

In [56]:
y_train.to_csv("y_training.csv",index=False)